/**
 * scripts/clean-pack.ts — Postpack cleanup for npm packaging.
 *
 * Removes the .js files generated by build-pack.ts and restores the original
 * package.json so the working tree returns to its TypeScript-only state after
 * `npm pack` completes.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { exit } from '../lib/hydra-process.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, '.packfiles');
const PKG_BACKUP = path.join(ROOT, '.package.json.bak');

// ── Restore original package.json ────────────────────────────────────────────

if (fs.existsSync(PKG_BACKUP)) {
  fs.renameSync(PKG_BACKUP, path.join(ROOT, 'package.json'));
  console.log('[postpack] Restored original package.json.');
}

// ── Remove generated .js files ───────────────────────────────────────────────

if (!fs.existsSync(MANIFEST_PATH)) {
  console.log('[postpack] No .packfiles manifest found — nothing to clean.');
  exit(0);
}

const files = fs.readFileSync(MANIFEST_PATH, 'utf8').split('\n').filter(Boolean);

let removed = 0;
for (const rel of files) {
  const abs = path.join(ROOT, rel);
  try {
    fs.unlinkSync(abs);
    removed += 1;
  } catch {
    // already gone
  }
}

fs.unlinkSync(MANIFEST_PATH);
console.log(`[postpack] Removed ${String(removed)} generated .js files.`);
