/**
 * gen-research-todo.ts
 * Generates docs/coordination/RESEARCH_TODO.md from all research docs
 * under docs/coordination/research/ (recursively).
 *
 * Fixes:
 * - Creates the research dir if missing (instead of failing)
 * - Uses relative links from the output file's location (research/...)
 *   not repo-root-prefixed paths that would double-resolve in GitHub/VS Code
 *
 * Usage: node scripts/gen-research-todo.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

const RESEARCH_DIR = path.join(REPO_ROOT, 'docs', 'coordination', 'research');
const OUTPUT_FILE = path.join(REPO_ROOT, 'docs', 'coordination', 'RESEARCH_TODO.md');
// Output file's directory — links are relative to this
const OUTPUT_DIR = path.dirname(OUTPUT_FILE);

const MARKER_START = '<!-- AUTOGENERATED: research-todo start -->';
const MARKER_END = '<!-- AUTOGENERATED: research-todo end -->';

const INCLUDE_EXTS = new Set(['.md', '.mdx', '.markdown', '.mdown', '.txt']);

// --- helpers ---

function toTitleCase(str: string) {
  return str.replace(/[-_]+/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase());
}

function extractTxtTitle(content: string): string | null {
  for (const line of content.split('\n')) {
    const t = line.trim();
    if (t !== '') return t;
  }
  return null;
}

function skipFrontMatter(lines: string[]): number {
  if (lines[0]?.trim() !== '---') return 0;
  let i = 1;
  while (i < lines.length && lines[i]?.trim() !== '---') i++;
  return i + 1;
}

function extractMarkdownTitle(content: string): string | null {
  const lines = content.split('\n');
  let i = skipFrontMatter(lines);
  let inCodeBlock = false;
  for (; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      continue;
    }
    if (inCodeBlock) continue;
    const m = /^#\s+(.+)$/.exec(line);
    if (m) return m[1].trim();
  }
  return null;
}

function extractTitle(filePath: string) {
  let raw;
  try {
    raw = fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }

  if (raw.charCodeAt(0) === 0xfeff) raw = raw.slice(1);
  if (raw.includes('\0')) return null;

  const content = raw.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const ext = path.extname(filePath).toLowerCase();

  return ext === '.txt' ? extractTxtTitle(content) : extractMarkdownTitle(content);
}

function collectFiles(dir: string): string[] {
  const results: string[] = [];
  if (!fs.existsSync(dir)) return results;

  function walk(current: string) {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isSymbolicLink()) continue; // skip symlinks
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile() && INCLUDE_EXTS.has(path.extname(entry.name).toLowerCase())) {
        results.push(full);
      }
    }
  }

  walk(dir);
  return results;
}

function groupFiles(files: string[]) {
  const groups: Record<string, { title: string; link: string }[]> = {};

  for (const f of files) {
    const rel = path.relative(RESEARCH_DIR, f); // e.g. "topic/file.md" or "file.md"
    const parts = rel.split(path.sep);
    const group = parts.length > 1 ? parts[0] : 'root';

    if (!(group in groups)) groups[group] = [];

    // Link is relative to OUTPUT_DIR
    const linkRel = path.relative(OUTPUT_DIR, f).replace(/\\/g, '/');
    const title = extractTitle(f) ?? toTitleCase(path.basename(f, path.extname(f)));

    groups[group].push({ title, link: linkRel });
  }

  // Sort each group by title
  for (const g of Object.values(groups)) {
    (g as { title: string; link: string }[]).sort((a: { title: string }, b: { title: string }) =>
      a.title.localeCompare(b.title, undefined, { sensitivity: 'base' }),
    );
  }

  return groups;
}

function renderBlock(groups: Record<string, { title: string; link: string }[]>) {
  const groupNames = Object.keys(groups).sort((a, b) => {
    if (a === 'root') return -1;
    if (b === 'root') return 1;
    return a.localeCompare(b, undefined, { sensitivity: 'base' });
  });

  const lines = [MARKER_START];

  if (groupNames.length === 0) {
    lines.push('');
    lines.push('_No research files found._');
  }

  for (const name of groupNames) {
    const items = groups[name];
    lines.push('');
    lines.push(`## ${name}`);
    lines.push('');
    for (const { title, link } of items) {
      lines.push(`- [ ] [${title}](${link})`);
    }
  }

  lines.push('');
  lines.push(MARKER_END);
  return lines.join('\n');
}

function countItems(groups: Record<string, unknown[]>) {
  let total = 0;
  for (const items of Object.values(groups)) total += items.length;
  return { total, groups: Object.keys(groups).length };
}

function buildOutput(groups: Record<string, { title: string; link: string }[]>) {
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const { total, groups: gc } = countItems(groups);

  const header = [
    '# Research TODO (autogenerated)',
    '',
    `> Generated: ${ts}  `,
    '> Do not edit between markers — content will be overwritten on next run.',
    '',
  ].join('\n');

  const block = renderBlock(groups);

  const footer = [
    '',
    '---',
    `_${String(total)} file${total === 1 ? '' : 's'} across ${String(gc)} group${gc === 1 ? '' : 's'}._`,
    '',
  ].join('\n');

  return header + block + footer;
}

function applyIdempotent(existing: string, newBlock: string) {
  const si = existing.indexOf(MARKER_START);
  const ei = existing.indexOf(MARKER_END);

  if (si === -1 || ei === -1) {
    // Markers missing — append block at end
    return `${existing.trimEnd()}\n\n${newBlock}\n`;
  }

  return existing.slice(0, si) + newBlock + existing.slice(ei + MARKER_END.length);
}

// --- main ---

function main() {
  // Create research dir if it doesn't exist
  if (!fs.existsSync(RESEARCH_DIR)) {
    fs.mkdirSync(RESEARCH_DIR, { recursive: true });
    console.log(`Created missing directory: docs/coordination/research/`);
  }

  const files = collectFiles(RESEARCH_DIR);
  const groups = groupFiles(files);

  let content;
  if (fs.existsSync(OUTPUT_FILE)) {
    const existing = fs.readFileSync(OUTPUT_FILE, 'utf8');
    const newBlock = renderBlock(groups);
    content = applyIdempotent(existing, newBlock);
  } else {
    content = buildOutput(groups);
  }

  // Ensure trailing newline
  if (!content.endsWith('\n')) content += '\n';

  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');

  const { total, groups: gc } = countItems(groups);
  console.log(`Written: docs/coordination/RESEARCH_TODO.md`);
  console.log(
    `  ${String(total)} file${total === 1 ? '' : 's'} across ${String(gc)} group${gc === 1 ? '' : 's'}`,
  );
}

main();
